import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Oswald } from 'next/font/google';
import './globals.css';

const gilroy = localFont({
	src: [
		{ path: './fonts/Gilroy-Bold.woff2', weight: '700', style: 'normal' },
		{ path: './fonts/Gilroy-SemiBold.woff2', weight: '600', style: 'normal' },
		{ path: './fonts/Gilroy-Medium.woff2', weight: '500', style: 'normal' },
		{ path: './fonts/Gilroy-Regular.woff2', weight: '400', style: 'normal' },
	],
	variable: '--font-gilroy',
});

const moderustic = localFont({
	src: [
		{
			path: './fonts/Moderustic-Regular.woff2',
			weight: '400',
			style: 'normal',
		},
	],
	variable: '--font-moderustic',
});

const oswald = Oswald({
	subsets: ['latin', 'cyrillic'],
	weight: ['700'],
	variable: '--font-oswald',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${gilroy.variable} ${moderustic.variable} ${oswald.variable}`}
			>
				{children}
			</body>
		</html>
	);
}
